import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

var dummyData = [
  Category(
    id: 'a',
    title: 'Amber',
    color: Colors.amber,
  ),
  Category(
    id: 'b',
    title: 'Blue',
    color: Colors.blue,
  ),
  Category(
    id: 'c',
    title: 'Cyan',
    color: Colors.cyan,
  ),
  Category(
    id: 'd',
    title: 'Denim',
    color: Color(0xFF1560BD),
  ),
  Category(
    id: 'e',
    title: 'Eclipse',
    color: Color(0xFF220F46),
  ),
  Category(
    id: 'f',
    title: 'Flax',
    color: Color(0xFFEEDC82),
  ),
  Category(
    id: 'g',
    title: 'Gold',
    color: Color(0xFFD4AF37),
  ),
  Category(
    id: 'h',
    title: 'Hazel',
    color: Color(0xffa52a2a),
  ),
  Category(
    id: 'i',
    title: 'Indigo',
    color: Color(0xff00416A),
  ),
  Category(
    id: 'j',
    title: 'Jade',
    color: Color(0xFF00A86B),
  ),
  Category(
    id: 'k',
    title: 'Khaki',
    color: Color(0xFFC3B091),
  ),
  Category(
    id: 'l',
    title: 'Lemon',
    color: Color(0xFFFDE910),
  ),
  Category(
    id: 'm',
    title: 'Maroon',
    color: Color(0xFF800000),
  ),
  Category(
    id: 'n',
    title: 'Navy Blue',
    color: Color(0xFF000080),
  ),
  Category(
    id: 'o',
    title: 'Orange',
    color: Colors.orange,
  ),
  Category(
    id: 'p',
    title: 'Pink',
    color: Colors.pink,
  ),
  Category(
    id: 'q',
    title: 'Quartile',
    color: Color(0xFF4CBB17),
  ),
  Category(
    id: 'r',
    title: 'Red',
    color: Colors.red,
  ),
  Category(
    id: 's',
    title: 'Saffron',
    color: Color(0xFFF4C430),
  ),
  Category(
    id: 't',
    title: 'Teal',
    color: Colors.teal,
  ),
  Category(
    id: 'u',
    title: 'Ultra Violet',
    color: Color(0xFF4b019c),
  ),
  Category(
    id: 'v',
    title: 'Violet',
    color: Color(0xFF8B00FF),
  ),
  Category(
    id: 'w',
    title: 'White',
    color: Colors.white,
  ),
  Category(
    id: 'x',
    title: 'Xanadu',
    color: Color(0xFF738678),
  ),
  Category(
    id: 'y',
    title: 'Yellow',
    color: Colors.yellow,
  ),
  Category(
    id: 'z',
    title: 'Zoboba',
    color: Color(0xFFbc8a52),
  ),
];

const DUMMY_ANIMALS = const [
  Animal(
    id: 'a',
    title: 'Alligator',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/alligator_10-400x300.jpg',
    description: 'The Alligator is an apex predator in its environment, known to even hunt animals that are much larger in size.',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish: false,
    isNative: false,
    isHunter: true,
    isInsect: false,
  ),
  Animal(
    id: 'a',
    title: 'Alpaca',
    imageUrl:
        'https://a-z-animals.com/media/alpalca-2-400x300.jpg',
    description: 'They can spit up to 10 feet.',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isNative: false,
    isHunter: false,
    isInsect: false,
  ),
  Animal(
    id: 'a',
    title: 'Ant',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/ant-400x300.jpg',
    description: 'There is a single “super ant colony” that stretches 3,700 miles along the Mediterranean coast.',
   eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isFish: false,
    isReptile: false,
    isInsect: true,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'b',
    title: 'Bat',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/bat5-400x300.jpg',
    description: 'A mother bat gives birth to her babies while hanging upside down',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: f,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'b',
    title: 'Buffalo',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/buffalo2-400x300.jpg',
    description: 'Has no real natural predators',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'b',
    title: 'Bulldog',
    imageUrl:
        'https://a-z-animals.com/media/bulldog-2-400x300.jpg',
    description: 'Commonly known as the English or British bulldog, the bulldog is a medium-sized and hefty dog with a muscular body. It has a wrinkled face and a nose that is ‘pushed-in',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'c',
    title: 'Camel',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/camel3-400x300.jpg',
    description: 'Can survive without water for 10 months!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'c',
    title: 'Cat',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Australian-Mist-header-400x300.jpg',
    description: ' When looking for their prey, the cat tends to seek out their prey on their own',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'c',
    title: 'Caterpillar',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Caterpillar-isolated-400x300.jpg',
    description: 'The larvae of a moth or butterfly!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'd',
    title: 'Deer',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/deer3-400x300.jpg',
    description: 'There are around 40 different species!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile:false ,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'd',
    title: 'Dog',
    imageUrl:
        'https://a-z-animals.com/media/2019/10/Alpine-Dachsbracke-close-up-400x300.jpg',
    description: 'Dogs are the domesticated descendants of the Wolf.',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'd',
    title: 'Duck',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Duck-in-pond-400x300.jpg',
    description: 'A duck can sleep with one eye open in order to stay alert to predators',
   eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'd',
    title: 'Dolphin',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Dolphin-smiling-400x300.jpg',
    description: 'Dolphins can travel in superpods of more than 1,000 individuals!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'e',
    title: 'Eagle',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Eagle-Bald-400x300.jpg',
    description: 'Has exceptional eyesight!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'e',
    title: 'Eel',
    imageUrl:
        'https://a-z-animals.com/media/eel-1-400x300.jpg',
    description: 'Eels can be a mere few inches long to 13 feet',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'e',
    title: 'Emu',
    imageUrl:
        'https://a-z-animals.com/media/emu-4-400x300.jpg',
    description: 'An emu has a running stride of 9 feet',
   eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'e',
    title: 'Elephant',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Elephant-Africa-400x300.jpg',
    description: 'Spends around 22 hours a day eating',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'f',
    title: 'Falcon',
    imageUrl:
        '',
    description: 'The falcon is faster than any other animal on earth, both on land and in the air',
   eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'f',
    title: 'Fox',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/fox_5-400x300.jpg',
    description: 'There are 12 different species in the world!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile:false ,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'f',
    title: 'Frog',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Frog-isolated-400x300.jpg',
    description: 'There are around 7,000 different species',
   eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish: false,
    isInsect: false,
    isNative:true,
    isHunter: true,

  ),
  Animal(
    id: 'g',
    title: 'Goat',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Goat-close-up-400x300.jpg',
    description: 'Most closely related to the Sheep',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'g',
    title: 'Goose',
    imageUrl:
        'https://a-z-animals.com/media/Goose-Graylag-400x300.jpg',
    description: 'During its migration, the goose flies in V formations to conserve energy.',
   eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'g',
    title: 'Guppy',
    imageUrl:
        'https://a-z-animals.com/media/guppy-1-400x300.jpg',
    description: 'Guppies give live birth to their young',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'g',
    title: 'Gorilla',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Gorilla-close-up-400x300.jpg',
    description: 'The biggest of the world\'s primates',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'h',
    title: 'Horse',
    imageUrl:
        'https://a-z-animals.com/media/horse-3-400x300.jpg',
    description: 'Has evolved over 50 million years',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'h',
    title: 'Hoopoe',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/hoopoe_6-400x300.jpg',
    description: 'The Hoopoe genus is the only living member of its family',
   eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish:false ,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'h',
    title: 'Hornbill',
    imageUrl:
        'https://a-z-animals.com/media/oriental-pied-hornbill-400x300.jpg',
    description: 'The bird has a massive horn on its bill',
   eatingHabit: EatingHabit.Harbivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish:false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'h',
    title: 'Hamster',
    imageUrl:
        'https://a-z-animals.com/media/hamster-3-400x300.jpg',
    description: 'Able to run as quickly backwards as forwards',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'h',
    title: 'Hummingbird',
    imageUrl:
        'https://a-z-animals.com/media/hummingbird-2-400x300.jpg',
    description: 'Hummingbird eggs are just half an inch big',
   eatingHabit: EatingHabit.Harbivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'h',
    title: 'Hyena',
    imageUrl:
        '',
    description: 'Hyenas are animals that are biologically closer to cats than dogs. In 1999, the lions and hyenas of Ethiopia’s Gobele wilderness went to war. The situation grew so deadly that the military intervened. In the end, the lions killed 35 hyenas, and the hyenas managed to kill six lions.',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false ,
    isHunter: true,

  ),
  Animal(
    id: 'i',
    title: 'Indri',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/indri-400x300.jpg',
    description: 'The largest species of Lemur!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'i',
    title: 'Iguana',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Iguana-Green-400x300.jpg',
    description: 'Uses visual signals to communicate!',
   eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish:false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'i',
    title: 'Impala',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/impala4-400x300.jpg',
    description: 'Able to jump over 10 feet high',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'j',
    title: 'Jaguar',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/jaguar6-400x300.jpg',
    description: 'The largest feline on the American continent!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'j',
    title: 'Jackal',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/jackal1-400x300.jpg',
    description: 'Can maintain speeds of 16 km/h!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'j',
    title: 'Jellyfish',
    imageUrl:
        '',
    description: 'Many jellyfish can produce their light.',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'k',
    title: 'Kangaroo',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Kangaroo-at-beach-400x300.jpg',
    description: 'Females have a deep pouch on their front!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile:false ,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'k',
    title: 'Kiwi',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Kiwi-close-up-400x300.jpg',
    description: ' The kiwi has a finely developed sense of smell, which is rare in birds',
   eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'k',
    title: 'Krill',
    imageUrl:
        'https://a-z-animals.com/media/krill-1-400x300.jpg',
    description: ' The krill is perhaps the most important animal in the marine ecosystem',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'k',
    title: 'King Crab',
    imageUrl:
        '',
    description: ' Can have a leg span of nearly 2 meters!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'l',
    title: 'Lemur',
    imageUrl:
        'https://a-z-animals.com/media/lemur-mom-and-baby-400x300.jpg',
    description: 'Natively found on the island of Madagascar',
   eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'l',
    title: 'Locust',
    imageUrl:
        'https://a-z-animals.com/media/2021/04/Locust-on-grass-400x300.jpg',
    description: 'Each locust can eat its weight in plants each day',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'l',
    title: 'Lungfish',
    imageUrl:
        'https://a-z-animals.com/media/South-American-Lungfish-400x300.jpg',
    description: 'The lungfish first evolved almost 400 million years ago.',
   eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'l',
    title: 'Leopard',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/leopard2-400x300.jpg',
    description: 'Spends much of the time high in the trees!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true ,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'l',
    title: 'Lion',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/lion1-400x300.jpg',
    description: 'Lives in small groups called prides!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile:false ,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'l',
    title: 'Lobster',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/lobster2-400x300.jpg',
    description: 'Have been known to reach 100 years old',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'm',
    title: 'Macaw',
    imageUrl:
        'https://a-z-animals.com/media/two-macaw-parrot-birds-400x300.jpg',
    description: ' The military macaw is named for the green uniforms that many soldiers use in South America.',
   eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'm',
    title: 'Magpie',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/magpie6-400x300.jpg',
    description: 'They are found across Europe, Asia and Africa!',
   eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish:false ,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'm',
    title: 'Moose',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/moose-400x300.jpg',
    description: ' Renews it\'s enormous antlers every year!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'm',
    title: 'Monkey',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/monkey4-400x300.jpg',
    description: 'There are around 260 known species!',
   eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,

  ),
  Animal(
    id: 'm',
    title: 'Mule',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/mule2-400x300.jpg',
    description: 'The offspring of a horse and donkey parents!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'm',
    title: 'Mouse',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Mouse-in-wood-400x300.jpg',
    description: 'Found on every continent on Earth!',
   eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,

  ),
  Animal(
    id: 'm',
    title: 'Meercat',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/meerkat2-399x300.jpg',
    description: 'One will stand on guard to watch for predators!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'm',
    title: 'Mongoose',
    imageUrl:
        'https://a-z-animals.com/media/Mongoose-Helogale-Parvula-400x300.jpg',
    description: 'Range in size from just 1 to 3 foot!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'n',
    title: 'Numbat',
    imageUrl:
        'https://a-z-animals.com/media/Numbat-Myrmecobius-Fasciatus-in-bushes-400x300.jpg',
    description: ' There are less than 1,000 left in the wild!',
   eatingHabit: EatingHabit.Omnivour,
     isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,

  ),
  Animal(
    id: 'n',
    title: 'Newt',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Newt-Common-400x300.jpg',
    description: 'Able to regrow lost or damaged limbs!',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'n',
    title: 'Narwhal',
    imageUrl:
        'https://a-z-animals.com/media/narwhal-1-400x300.jpg',
    description: 'Lives and hunts in the frigid Arctic!',
   eatingHabit: EatingHabit.Carnivour,
     isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'n',
    title: 'Nurse Shark',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/nurse_shark1-400x300.jpg',
    description: 'Commonly found in Central American waters',
   eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  Animal(
    id: 'a',
    title: '',
    imageUrl:
        '',
    description: '',
   eatingHabit: EatingHabit.Carnivour,
    isBird: ,
    isMammal: ,
    isReptile: ,
    isFish: ,
    isInsect: ,
    isNative: ,
    isHunter: ,

  ),
  
];
