import 'package:flutter/material.dart';

import './models/category.dart';
import 'models/animal.dart';

var dummyData = [
  Category(
    id: 'a',
    title: 'Amber',
    color: Colors.amber,
  ),
  Category(
    id: 'b',
    title: 'Blue',
    color: Colors.blue,
  ),
  Category(
    id: 'c',
    title: 'Cyan',
    color: Colors.cyan,
  ),
  Category(
    id: 'd',
    title: 'Denim',
    color: Color(0xFF1560BD),
  ),
  Category(
    id: 'e',
    title: 'Eclipse',
    color: Color(0xFF220F46),
  ),
  Category(
    id: 'f',
    title: 'Flax',
    color: Color(0xFFEEDC82),
  ),
  Category(
    id: 'g',
    title: 'Gold',
    color: Color(0xFFD4AF37),
  ),
  Category(
    id: 'h',
    title: 'Hazel',
    color: Color(0xffa52a2a),
  ),
  Category(
    id: 'i',
    title: 'Indigo',
    color: Color(0xff00416A),
  ),
  Category(
    id: 'j',
    title: 'Jade',
    color: Color(0xFF00A86B),
  ),
  Category(
    id: 'k',
    title: 'Khaki',
    color: Color(0xFFC3B091),
  ),
  Category(
    id: 'l',
    title: 'Lemon',
    color: Color(0xFFFDE910),
  ),
  Category(
    id: 'm',
    title: 'Maroon',
    color: Color(0xFF800000),
  ),
  Category(
    id: 'n',
    title: 'Navy Blue',
    color: Color(0xFF000080),
  ),
  Category(
    id: 'o',
    title: 'Orange',
    color: Colors.orange,
  ),
  Category(
    id: 'p',
    title: 'Pink',
    color: Colors.pink,
  ),
  Category(
    id: 'q',
    title: 'Quartile',
    color: Color(0xFF4CBB17),
  ),
  Category(
    id: 'r',
    title: 'Red',
    color: Colors.red,
  ),
  Category(
    id: 's',
    title: 'Saffron',
    color: Color(0xFFF4C430),
  ),
  Category(
    id: 't',
    title: 'Teal',
    color: Colors.teal,
  ),
  Category(
    id: 'u',
    title: 'Ultra Violet',
    color: Color(0xFF4b019c),
  ),
  Category(
    id: 'v',
    title: 'Violet',
    color: Color(0xFF8B00FF),
  ),
  Category(
    id: 'w',
    title: 'White',
    color: Colors.white,
  ),
  Category(
    id: 'x',
    title: 'Xanadu',
    color: Color(0xFF738678),
  ),
  Category(
    id: 'y',
    title: 'Yellow',
    color: Colors.yellow,
  ),
  Category(
    id: 'z',
    title: 'Zoboba',
    color: Color(0xFFbc8a52),
  ),
];

const DUMMY_ANIMALS = const [
  Animal(
    id: 'a1',
    category: 'a',
    title: 'Alligator',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/alligator_10-400x300.jpg',
    description:
        'The Alligator is an apex predator in its environment, known to even hunt animals that are much larger in size.',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish: false,
    isNative: false,
    isHunter: true,
    isInsect: false,
  ),
  Animal(
    id: 'a2',
    category: 'a',
    title: 'Alpaca',
    imageUrl: 'https://a-z-animals.com/media/alpalca-2-400x300.jpg',
    description: 'They can spit up to 10 feet.',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isNative: false,
    isHunter: false,
    isInsect: false,
  ),
  Animal(
    id: 'a3',
    category: 'a',
    title: 'Ant',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/ant-400x300.jpg',
    description:
        'There is a single “super ant colony” that stretches 3,700 miles along the Mediterranean coast.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isFish: false,
    isReptile: false,
    isInsect: true,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a4',
    category: 'b',
    title: 'Bat',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/bat5-400x300.jpg',
    description:
        'A mother bat gives birth to her babies while hanging upside down',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a5',
    category: 'b',
    title: 'Buffalo',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/buffalo2-400x300.jpg',
    description: 'Has no real natural predators',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a6',
    category: 'b',
    title: 'Bulldog',
    imageUrl: 'https://a-z-animals.com/media/bulldog-2-400x300.jpg',
    description:
        'Commonly known as the English or British bulldog, the bulldog is a medium-sized and hefty dog with a muscular body. It has a wrinkled face and a nose that is ‘pushed-in',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a7',
    category: 'c',
    title: 'Camel',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/camel3-400x300.jpg',
    description: 'Can survive without water for 10 months!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a8',
    category: 'c',
    title: 'Cat',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Australian-Mist-header-400x300.jpg',
    description:
        ' When looking for their prey, the cat tends to seek out their prey on their own',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a9',
    category: 'c',
    title: 'Caterpillar',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Caterpillar-isolated-400x300.jpg',
    description: 'The larvae of a moth or butterfly!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a10',
    category: 'd',
    title: 'Deer',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/deer3-400x300.jpg',
    description: 'There are around 40 different species!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a11',
    category: 'd',
    title: 'Dog',
    imageUrl:
        'https://a-z-animals.com/media/2019/10/Alpine-Dachsbracke-close-up-400x300.jpg',
    description: 'Dogs are the domesticated descendants of the Wolf.',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a12',
    category: 'd',
    title: 'Duck',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Duck-in-pond-400x300.jpg',
    description:
        'A duck can sleep with one eye open in order to stay alert to predators',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a13',
    category: 'd',
    title: 'Dolphin',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Dolphin-smiling-400x300.jpg',
    description:
        'Dolphins can travel in superpods of more than 1,000 individuals!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a14',
    category: 'e',
    title: 'Eagle',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Eagle-Bald-400x300.jpg',
    description: 'Has exceptional eyesight!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a15',
    category: 'e',
    title: 'Eel',
    imageUrl: 'https://a-z-animals.com/media/eel-1-400x300.jpg',
    description: 'Eels can be a mere few inches long to 13 feet',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a16',
    category: 'e',
    title: 'Emu',
    imageUrl: 'https://a-z-animals.com/media/emu-4-400x300.jpg',
    description: 'An emu has a running stride of 9 feet',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a17',
    category: 'e',
    title: 'Elephant',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Elephant-Africa-400x300.jpg',
    description: 'Spends around 22 hours a day eating',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a18',
    category: 'f',
    title: 'Falcon',
    imageUrl: '',
    description:
        'The falcon is faster than any other animal on earth, both on land and in the air',
    eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a19',
    category: 'f',
    title: 'Fox',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/fox_5-400x300.jpg',
    description: 'There are 12 different species in the world!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a20',
    category: 'f',
    title: 'Frog',
    imageUrl: 'https://a-z-animals.com/media/2018/09/Frog-isolated-400x300.jpg',
    description: 'There are around 7,000 different species',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a21',
    category: 'g',
    title: 'Goat',
    imageUrl: 'https://a-z-animals.com/media/2018/09/Goat-close-up-400x300.jpg',
    description: 'Most closely related to the Sheep',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a22',
    category: 'g',
    title: 'Goose',
    imageUrl: 'https://a-z-animals.com/media/Goose-Graylag-400x300.jpg',
    description:
        'During its migration, the goose flies in V formations to conserve energy.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a23',
    category: 'g',
    title: 'Guppy',
    imageUrl: 'https://a-z-animals.com/media/guppy-1-400x300.jpg',
    description: 'Guppies give live birth to their young',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a24',
    category: 'g',
    title: 'Gorilla',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Gorilla-close-up-400x300.jpg',
    description: 'The biggest of the world\'s primates',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a25',
    category: 'h',
    title: 'Horse',
    imageUrl: 'https://a-z-animals.com/media/horse-3-400x300.jpg',
    description: 'Has evolved over 50 million years',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a26',
    category: 'h',
    title: 'Hoopoe',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/hoopoe_6-400x300.jpg',
    description: 'The Hoopoe genus is the only living member of its family',
    eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a27',
    category: 'h',
    title: 'Hornbill',
    imageUrl:
        'https://a-z-animals.com/media/oriental-pied-hornbill-400x300.jpg',
    description: 'The bird has a massive horn on its bill',
    eatingHabit: EatingHabit.Harbivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a28',
    category: 'h',
    title: 'Hagfish',
    imageUrl: 'https://a-z-animals.com/media/hagfish-4-400x300.jpg',
    description:
        'Can use slime to suffocate marine predators or escape capture',
    eatingHabit: EatingHabit.Harbivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a29',
    category: 'h',
    title: 'Hamster',
    imageUrl: 'https://a-z-animals.com/media/hamster-3-400x300.jpg',
    description: 'Able to run as quickly backwards as forwards',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a30',
    category: 'h',
    title: 'Hummingbird',
    imageUrl: 'https://a-z-animals.com/media/hummingbird-2-400x300.jpg',
    description: 'Hummingbird eggs are just half an inch big',
    eatingHabit: EatingHabit.Harbivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a31',
    category: 'h',
    title: 'Hyena',
    imageUrl: '',
    description:
        'Hyenas are animals that are biologically closer to cats than dogs. In 1999, the lions and hyenas of Ethiopia’s Gobele wilderness went to war. The situation grew so deadly that the military intervened. In the end, the lions killed 35 hyenas, and the hyenas managed to kill six lions.',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a32',
    category: 'i',
    title: 'Indri',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/indri-400x300.jpg',
    description: 'The largest species of Lemur!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a33',
    category: 'i',
    title: 'Iguana',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Iguana-Green-400x300.jpg',
    description: 'Uses visual signals to communicate!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a34',
    category: 'i',
    title: 'Impala',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/impala4-400x300.jpg',
    description: 'Able to jump over 10 feet high',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a35',
    category: 'j',
    title: 'Jaguar',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/jaguar6-400x300.jpg',
    description: 'The largest feline on the American continent!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a36',
    category: 'j',
    title: 'Jackal',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/jackal1-400x300.jpg',
    description: 'Can maintain speeds of 16 km/h!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a37',
    category: 'j',
    title: 'Jellyfish',
    imageUrl: '',
    description: 'Many jellyfish can produce their light.',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a38',
    category: 'k',
    title: 'Kangaroo',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Kangaroo-at-beach-400x300.jpg',
    description: 'Females have a deep pouch on their front!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a39',
    category: 'k',
    title: 'Kiwi',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Kiwi-close-up-400x300.jpg',
    description:
        ' The kiwi has a finely developed sense of smell, which is rare in birds',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a40',
    category: 'k',
    title: 'Krill',
    imageUrl: 'https://a-z-animals.com/media/krill-1-400x300.jpg',
    description:
        ' The krill is perhaps the most important animal in the marine ecosystem',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a41',
    category: 'k',
    title: 'King Crab',
    imageUrl: '',
    description: ' Can have a leg span of nearly 2 meters!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a42',
    category: 'l',
    title: 'Lemur',
    imageUrl: 'https://a-z-animals.com/media/lemur-mom-and-baby-400x300.jpg',
    description: 'Natively found on the island of Madagascar',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a43',
    category: 'l',
    title: 'Locust',
    imageUrl:
        'https://a-z-animals.com/media/2021/04/Locust-on-grass-400x300.jpg',
    description: 'Each locust can eat its weight in plants each day',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a44',
    category: 'l',
    title: 'Lungfish',
    imageUrl:
        'https://a-z-animals.com/media/South-American-Lungfish-400x300.jpg',
    description: 'The lungfish first evolved almost 400 million years ago.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a45',
    category: 'l',
    title: 'Leopard',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/leopard2-400x300.jpg',
    description: 'Spends much of the time high in the trees!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a46',
    category: 'l',
    title: 'Lion',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/lion1-400x300.jpg',
    description: 'Lives in small groups called prides!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a47',
    category: 'l',
    title: 'Lobster',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/lobster2-400x300.jpg',
    description: 'Have been known to reach 100 years old',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a48',
    category: 'm',
    title: 'Macaw',
    imageUrl:
        'https://a-z-animals.com/media/two-macaw-parrot-birds-400x300.jpg',
    description:
        ' The military macaw is named for the green uniforms that many soldiers use in South America.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a49',
    category: 'm',
    title: 'Magpie',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/magpie6-400x300.jpg',
    description: 'They are found across Europe, Asia and Africa!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a50',
    category: 'm',
    title: 'Moose',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/moose-400x300.jpg',
    description: ' Renews it\'s enormous antlers every year!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a51',
    category: 'm',
    title: 'Monkey',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/monkey4-400x300.jpg',
    description: 'There are around 260 known species!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a52',
    category: 'm',
    title: 'Mule',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/mule2-400x300.jpg',
    description: 'The offspring of a horse and donkey parents!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a53',
    category: 'm',
    title: 'Mouse',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Mouse-in-wood-400x300.jpg',
    description: 'Found on every continent on Earth!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a54',
    category: 'm',
    title: 'Meercat',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/meerkat2-399x300.jpg',
    description: 'One will stand on guard to watch for predators!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a55',
    category: 'm',
    title: 'Mongoose',
    imageUrl:
        'https://a-z-animals.com/media/Mongoose-Helogale-Parvula-400x300.jpg',
    description: 'Range in size from just 1 to 3 foot!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a56',
    category: 'n',
    title: 'Numbat',
    imageUrl:
        'https://a-z-animals.com/media/Numbat-Myrmecobius-Fasciatus-in-bushes-400x300.jpg',
    description: ' There are less than 1,000 left in the wild!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a57',
    category: 'n',
    title: 'Newt',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Newt-Common-400x300.jpg',
    description: 'Able to regrow lost or damaged limbs!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a58',
    category: 'n',
    title: 'Narwhal',
    imageUrl: 'https://a-z-animals.com/media/narwhal-1-400x300.jpg',
    description: 'Lives and hunts in the frigid Arctic!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a59',
    category: 'n',
    title: 'Nurse Shark',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/nurse_shark1-400x300.jpg',
    description: 'Commonly found in Central American waters',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a60',
    category: 'o',
    title: 'Octopus',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/octopus1-400x300.jpg',
    description: ' There are around 300 different species!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a61',
    category: 'o',
    title: 'Ostrich',
    imageUrl:
        'https://a-z-animals.com/media/2020/01/Ostrich-walking-400x300.jpg',
    description:
        'The ostrich is among the largest types of birds in the world.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a62',
    category: 'o',
    title: 'Orang-utan',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/orang-utan5-400x300.jpg',
    description: 'Shares 97% of its DNA with humans',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a63',
    category: 'o',
    title: 'Oyster',
    imageUrl:
        'https://a-z-animals.com/media/Oyster-Ostreidae-thorny-oyster-400x300.jpg',
    description: ' They have eyes all over their bodies',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a64',
    category: 'o',
    title: 'Otter',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/otter_10-400x300.jpg',
    description: ' There are 13 different species worldwide',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a65',
    category: 'p',
    title: 'Panther',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/panther-400x300.jpg',
    description: 'Prefers to hunt at night than during the day',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a66',
    category: 'p',
    title: 'Parrot',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Parrot-Sun-Conure-400x300.jpg',
    description: ' Can live for up to 100 years',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a67',
    category: 'p',
    title: 'Pigeon',
    imageUrl: 'https://a-z-animals.com/media/2021/01/Pigeon-flock-400x300.jpg',
    description:
        'They can find their way back to their nests from up to 1300 miles away.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a68',
    category: 'p',
    title: 'Pelican',
    imageUrl:
        'https://a-z-animals.com/media/2019/11/Pelican-in-flight-400x300.jpg',
    description: 'Can have a wingspan of up to 3 meters!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a69',
    category: 'p',
    title: 'Peacock',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Peacock-feathers-400x300.jpg',
    description: 'A group of peafowls is called a muster.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a70',
    category: 'p',
    title: 'Puma',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/puma_10-400x300.jpg',
    description: ' Has longer back legs than front legs',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a71',
    category: 'q',
    title: 'Quail',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/quail1-400x300.jpg',
    description: ' Inhabits woodland and forest areas worldwide',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a72',
    category: 'q',
    title: 'Quetzal',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/quetzal2-400x300.jpg',
    description: 'The tail feathers of the male can be 1m long',
    eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a73',
    category: 'r',
    title: 'Rabbit',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original_backup/rabbit2-400x300.jpg',
    description: ' There are more than 50 different species',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a74',
    category: 'r',
    title: 'Raccoon',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Raccoon-close-up-400x300.jpg',
    description:
        'Sporting a black mask and ringed tail, the raccoon is among the most common mammals in North America',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a75',
    category: 'r',
    title: 'Rat',
    imageUrl: 'https://a-z-animals.com/media/rat-7-400x300.jpg',
    description: 'Omnivores that eat anything!',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a76',
    category: 'r',
    title: 'Reindeer',
    imageUrl: '',
    description: 'Also known as the Caribou',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a77',
    category: 'r',
    title: 'Robin',
    imageUrl: '',
    description:
        'The robin can migrate up to 3,000 miles to its wintering grounds',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a78',
    category: 's',
    title: 'Snail',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Snail-Roman-400x300.jpg',
    description: 'There are nearly 1,000 different species!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a79',
    category: 's',
    title: 'Snake',
    imageUrl:
        'https://a-z-animals.com/media/2020/01/Snake-Blue-viper-400x300.jpg',
    description: 'There are around 3,000 known species worldwide',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: true,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a80',
    category: 's',
    title: 'Sparrow',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Sparrow-on-branch-400x300.jpg',
    description: 'There are more sparrows in the world than people.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a81',
    category: 's',
    title: 'Squid',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/squid-400x300.jpg',
    description: 'Some species are known to have 10 arms',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a82',
    category: 's',
    title: 'Squirrel',
    imageUrl: 'https://a-z-animals.com/media/2019/11/Squirrel-red-400x300.jpg',
    description: 'Small rodents found in woodlands worldwide',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a83',
    category: 's',
    title: 'Sheep',
    imageUrl: 'https://a-z-animals.com/media/sheep-1-400x300.jpg',
    description:
        'Sheep were one of the first and most successful domesticated species in the world.',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: false,
  ),
  Animal(
    id: 'a84',
    category: 't',
    title: 'Tiger',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/tiger3-400x300.jpg',
    description: 'The largest feline in the world!',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a85',
    category: 't',
    title: 'Turkey',
    imageUrl: 'https://a-z-animals.com/media/turkey-isolated-400x300.jpg',
    description:
        'A turkey\'s gender can be determined by the shape of its droppings',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a86',
    category: 't',
    title: 'Tuna',
    imageUrl: 'https://a-z-animals.com/media/2021/01/Tuna-in-ocean-400x300.jpg',
    description:
        ' The tuna has a sleek body that enables it to swim quickly through the water',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: true,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a87',
    category: 'v',
    title: 'Vulture',
    imageUrl: 'https://a-z-animals.com/media/Vulture-3-400x300.jpg',
    description: 'There are 30 different species worldwide',
    eatingHabit: EatingHabit.Carnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a88',
    category: 'w',
    title: 'Walrus',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/walrus-400x300.jpg',
    description: 'Inhabits the freezing waters of the Arctic Circle',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a89',
    category: 'w',
    title: 'Wasp',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/wasp-400x300.jpg',
    description: ' There are around 75,000 recognised species',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: true,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a90',
    category: 'w',
    title: 'Wolf',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/wolf_8-400x300.jpg',
    description:
        'Wolves are apex predators that travel in packs and are essential for the health of most ecosystems',
    eatingHabit: EatingHabit.Carnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: true,
  ),
  Animal(
    id: 'a91',
    category: 'w',
    title: 'Woodpecker',
    imageUrl:
        'https://a-z-animals.com/media/2018/09/Woodpecker-spotted-400x300.jpg',
    description:
        ' They have zygodactyl feet, with the first and fourth toes facing backward, the second and third facing forward, so they can grip tree trunks more efficiently',
    eatingHabit: EatingHabit.Omnivour,
    isBird: true,
    isMammal: false,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: true,
    isHunter: true,
  ),
  Animal(
    id: 'a92',
    category: 'x',
    title: 'Xerus',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/xerus-400x300.jpg',
    description:
        'Xerus use their fluffy tail as shade from the sun on the African savanna.',
    eatingHabit: EatingHabit.Omnivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a93',
    category: 'y',
    title: 'Yak',
    imageUrl: 'https://a-z-animals.com/media/Yak1-400x300.jpg',
    description: 'There are only a few left in the wild',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  Animal(
    id: 'a94',
    category: 'z',
    title: 'Zebra',
    imageUrl:
        'https://a-z-animals.com/media/animals/images/original/zebra_8-400x300.jpg',
    description: 'Stripe patterns are unique to each individual!',
    eatingHabit: EatingHabit.Harbivour,
    isBird: false,
    isMammal: true,
    isReptile: false,
    isFish: false,
    isInsect: false,
    isNative: false,
    isHunter: false,
  ),
  // Animal(
  //   id: '',
  //   title: '',
  //   imageUrl:
  //       '',
  //   description: '',
  //  eatingHabit: EatingHabit.Harbivour,
  //   isBird: ,
  //   isMammal: ,
  //   isReptile: ,
  //   isFish: ,
  //   isInsect: ,
  //   isNative: ,
  //   isHunter: ,

  // ),
];
